## What is PyTorch?
it's python based scientific computing package targeted as two oset of audiences:


*   A replacement of NumPy to use the power GPUs
*   A deep learning researc platform that provides maximum flexibility and speed




### Tensor

Tensor are similar to NUmPy's ndarrays, with addition being that Tensors can also be used on A GPU to accelerate computing

In [1]:
from __future__ import print_function
import torch

construct a 5x3 matrix, uninitialized.

In [2]:
x = torch.empty(5, 3)
x

tensor([[1.7604e-37, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.6133e-36]])

construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3695, 0.1000, 0.5117],
        [0.9728, 0.6000, 0.9488],
        [0.8275, 0.6408, 0.5906],
        [0.7063, 0.1848, 0.5980],
        [0.4188, 0.2305, 0.3213]])

construct a matrix fulled zeros and dtype long

In [4]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

construct tensor directly from data

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [7]:
x = x.new_ones(5, 3, dtype = torch.double)  # new_ + method taka in size
print(x)

x = torch.randn_like(x, dtype = torch.float)  # override dtype:
print(x)                                      # result has rhe same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0179,  1.2472,  1.1268],
        [-0.3973, -1.1798,  0.4555],
        [-0.0844,  0.8238, -0.6912],
        [ 0.7279,  0.3065,  0.2901],
        [ 1.6041, -2.0209, -0.2634]])


In [8]:
# Get its size
x.size()

torch.Size([5, 3])

Note:


> torch.Size is in fact a tuple, so it supports all tuple operations.



### Operations
there are multiple syntaxes for the operations. In the following example, we will take a look at the addition operation.

addition syntax 1

In [9]:
y = torch.rand(5, 3)
x + y

tensor([[ 1.8342,  1.8122,  1.2623],
        [ 0.0466, -0.5550,  1.3462],
        [ 0.1267,  1.3586, -0.1761],
        [ 1.4779,  1.1529,  0.5853],
        [ 1.6335, -1.8801, -0.1944]])

addition syntax 2

In [10]:
torch.add(x, y)

tensor([[ 1.8342,  1.8122,  1.2623],
        [ 0.0466, -0.5550,  1.3462],
        [ 0.1267,  1.3586, -0.1761],
        [ 1.4779,  1.1529,  0.5853],
        [ 1.6335, -1.8801, -0.1944]])

addition 3, providing an output tensor as argument

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
result

tensor([[ 1.8342,  1.8122,  1.2623],
        [ 0.0466, -0.5550,  1.3462],
        [ 0.1267,  1.3586, -0.1761],
        [ 1.4779,  1.1529,  0.5853],
        [ 1.6335, -1.8801, -0.1944]])

additionn 4, in-place

In [12]:
y.add_(x)   # this will chane the original value of y

tensor([[ 1.8342,  1.8122,  1.2623],
        [ 0.0466, -0.5550,  1.3462],
        [ 0.1267,  1.3586, -0.1761],
        [ 1.4779,  1.1529,  0.5853],
        [ 1.6335, -1.8801, -0.1944]])

we can use standard NumPy-like indexing with all bells and whistles!

In [13]:
x[:, 1]

tensor([ 1.2472, -1.1798,  0.8238,  0.3065, -2.0209])

we can resize/reshape our tensor with ***torch.view***

In [14]:
x = torch.rand(4, 4)
print(x.size())
y = x.view(16)
print(y.size())
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


tp get value from one element tensor, use ***.item()***  to get value as a Python number

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1247])
0.12473121285438538


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

### NumPy Bridge

Converting a Torch to a Numpy array and a NumPy to Tensor.

    The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [16]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [17]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array changed in value.

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting a Numpy Array to Torch Tensor

In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)

print(a , b)

np.add(a, 1, out = a)
print(a)
print(b)


[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.1247], device='cuda:0')
tensor([1.1247], dtype=torch.float64)


### How to check GPU with Pytorch

In [24]:
torch.cuda.current_device()

0

In [25]:
torch.cuda.device(0)

In [27]:
torch.cuda.device_count()

1

In [33]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [29]:
torch.cuda.is_available()

True

## Autograd : Automatic Differentiation

Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

### Tensor


``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with
``requires_grad=True``, but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.

In [40]:
import torch

create a tensor and set requires_grad = True, to track computation with it

In [62]:
x = torch.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [63]:
x.grad

In [64]:
# Do a tensor operation
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

``y`` was created as aresult of an operation, so it has a grad_fn

In [65]:
y.grad_fn

Do more operations on ``y``

In [66]:
z = y * y * 3
out = z.mean()

print(z)
out

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


tensor(27., grad_fn=<MeanBackward0>)

``.requires_grad_( ... )`` changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

In [67]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
print(a.grad_fn)

a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [70]:
a , b

(tensor([[ 0.1111, -5.8430],
         [-5.7809, -4.3973]], requires_grad=True),
 tensor(86.9080, grad_fn=<SumBackward0>))

### Gradient

Let's backprop now.
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1.))``


In [68]:
out.backward()

In [69]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



Mathematically, if you have a vector valued function $\vec{y}=f(\vec{x})$,
then the gradient of $\vec{y}$ with respect to $\vec{x}$
is a Jacobian matrix:

\begin{align}J=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right)\end{align}

Generally speaking, ``torch.autograd`` is an engine for computing
vector-Jacobian product. That is, given any vector
$v=\left(\begin{array}{cccc} v_{1} & v_{2} & \cdots & v_{m}\end{array}\right)^{T}$,
compute the product $v^{T}\cdot J$. If $v$ happens to be
the gradient of a scalar function $l=g\left(\vec{y}\right)$,
that is,
$v=\left(\begin{array}{ccc}\frac{\partial l}{\partial y_{1}} & \cdots & \frac{\partial l}{\partial y_{m}}\end{array}\right)^{T}$,
then by the chain rule, the vector-Jacobian product would be the
gradient of $l$ with respect to $\vec{x}$:

\begin{align}J^{T}\cdot v=\left(\begin{array}{ccc}
   \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{1}}\\
   \vdots & \ddots & \vdots\\
   \frac{\partial y_{1}}{\partial x_{n}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
   \end{array}\right)\left(\begin{array}{c}
   \frac{\partial l}{\partial y_{1}}\\
   \vdots\\
   \frac{\partial l}{\partial y_{m}}
   \end{array}\right)=\left(\begin{array}{c}
   \frac{\partial l}{\partial x_{1}}\\
   \vdots\\
   \frac{\partial l}{\partial x_{n}}
   \end{array}\right)\end{align}

(Note that $v^{T}\cdot J$ gives a row vector which can be
treated as a column vector by taking $J^{T}\cdot v$.)

This characteristic of vector-Jacobian product makes it very
convenient to feed external gradients into a model that has
non-scalar output.



In [78]:
x = torch.randn(3, requires_grad=True)

print(x)
y = x * 2
print(y)
while y.data.norm() < 1000:
  y = y * 2

y

tensor([-0.2121, -0.0440,  1.0662], requires_grad=True)
tensor([-0.4242, -0.0881,  2.1324], grad_fn=<MulBackward0>)


tensor([-217.1754,  -45.0898, 1091.7831], grad_fn=<MulBackward0>)

Now in this case ``y`` is no longer scalar. torch.autograd could not compute the full jacobian directly, but if we want the vector Jacobin Product, simple pass the vector to backward as argument

In [79]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)

y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


You can also stop autograd from tracking history on Tensors with ``.requires_grad=True`` either by wrapping the code block in with ``torch.no_grad():``

In [88]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


Or by using ``.detach()`` to get a new Tensor with the same content but that does not require gradients:

In [89]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [91]:
#  To check tensor equalilty
t1 = torch.tensor([1.3, 3])
t2 = torch.tensor([1.3, 3])

t1.eq(t2), t1.eq(t2).all()

(tensor([True, True]), tensor(True))